### ISSUE TITLE
Reading failed [nsqd.nsq:4150](2)

### ISSUE THREAD

**Issue by askie** [moolex/nsqclient-php#4]
error：
Reading failed [nsqd.nsq:4150](2)

but  nsqd.nsq:4150  is working,
I'm run php on  cli. 

how to config?

**Comment by moolex** [comment]
What log message the nsqd server shows when client showing "Reading failed" ?

**Comment by askie** [comment]
ERROR: client(192.168.3.20:59284) - failed to read command - read tcp 192.168.3.20:4150->192.168.3.20:59284: i/o timeout

**Comment by askie** [comment]
it's a more than 60s task。
if task need more than 60s， will be the error

**Comment by moolex** [comment]
Nsqd has options that are "max-heartbeat-interval" and "msg-timeout"

See http://nsq.io/components/nsqd.html

Try to increase timeout setting in nsqd server but recommend to make your job most quicky to finish

**Comment by askie** [comment]
but when I use golang client to complete a more than 1m task, all are ok .
so , I think the php cantact with nsq server,something wrong!

**Comment by moolex** [comment]
PHP code is running with single thread, when you are do something like DB operating or other blocking TCP conn, the heartbeat package from nsqd server will not process in time, if more than 60s the nsqd server will disconnect client because of options "max-heartbeat-interval"
